# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:


    - task: Docker@2
      inputs:
       containerRegistry: 'Dockerhub'
       repository: 'azuredevopstest'
       command: 'build'
       Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
       tags: 'nityasinghdev/azuredevopstest:$(Build.BuildId)'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello nitya'
          docker image ls
    - task: Docker@2
      inputs:
          containerRegistry: 'Dockerhub'
          repository: 'azuredevopstest'
          command: 'push'
          tags: 'nityasinghdev/azuredevopstest:$(Build.BuildId)'
    # - task: CopyFiles@2
    #   inputs:
    #     Contents: 'deployment.azure.yaml'
    #     TargetFolder: '$(build.artifactstagingdirectory)'
    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'